compilers=&enzyme-opt
defaultCompiler=enzyme-opt16
compilerType=mlir

supportsBinary=false
supportsExecute=false
supportsAsmDocs=false

group.enzyme-opt.compilers=enzyme-opt16-main
group.enzyme-opt.isSemVer=true
group.enzyme-opt.baseName=enzyme-opt

compiler.enzyme-opt16-main.exe=/opt/compiler-explorer/main/enzyme-opt16
compiler.enzyme-opt16-main.semver=16.0.0
